const sound_bytes = {
  '1%': { url: 'glados_chat_04.mp3' },
  '100%': { url: 'glados_chat_01.mp3' },
  '17%': { url: 'glados_chat_07.mp3' },
  '2sad': { url: 'sad_trombone_-_gaming_sound_effect_hd.mp3' },
  '3sad': { url: 'tf_nemesis_Oe7WCXy.mp3' },
  420: { url: 'smoke-weed-everyday-cut-mp3.mp3' },
  9000: { url: 'over9000.swf.mp3' },
  alright: {
    url: 'alright_alright_alright_-_dazed_and_confused.mp3',
  },
  another: { url: 'another-one_dPvHt2Z.mp3', volume: 0.8 },
  beautiful: { url: 'gaben_beautiful_person.mp3' },
  brb: { url: 'ill-be-back.mp3', volume: 0.75 },
  brutal: { url: 'brutal.mp3' },
  champ: { url: 'champ-is-champ-there-mp3cut.mp3' },
  cheer: { url: 'kids_cheering.mp3' },
  confused: { url: 'so_confused.mp3' },
  corona: { url: 'whatsapp-video-2020-03-11-at-19.mp3' },
  crab: { url: 'gaben_space_crab.mp3' },
  damn: { url: 'friday-damn.mp3' },
  danger: { url: 'im_in_danger.mp3' },
  daniel: { url: 'damndaniel.mp3' },
  disaster: { url: 'disastah.mp3' },
  doit: { url: 'senator-palpatine-do-it.mp3' },
  dota: { url: 'lets_play.mp3' },
  doto: { url: 'horn-of-morvalacenarius-dota.mp3' },
  ezmoney: { url: 'easiest_money.mp3' },
  f: { url: '5a3a6217-9b3e-431a-a8f1-657edc826be4.mp3' },
  feelingitnow: { url: 'are-you-feeling-it-now-mr-krabs.mp3' },
  friday: { url: 'friday-r.mp3' },
  goodmorning: { url: 'goodmorn1.mp3' },
  goodness: { url: 'goodness.mp3' },
  groan: { url: 'misc_soundboard_ti9_crowd_groan.mp3' },
  guh: { url: 'guh.wav' },
  haha: { url: 'the-simpsons-nelsons-haha.mp3' },
  hahgay: { url: 'senor-chang-gay_1.mp3' },
  hello: { url: 'hello-button.mp3' },
  hey: { url: 'rngm-heyyeyaaeyaaaeyaeyaa-mp3cut.mp3' },
  holymoly: { url: 'holy_moly.mp3' },
  how: { url: 'how-could-this-happen-to-me-with-lyrics-46.mp3' },
  imback: { url: "I'm back...(AKA Terminator 3).mp3" },
  imback2: { url: "Hello Boys I'm Back.mp3" },
  inception: { url: 'inceptionbutton.mp3' },
  jc: { url: 'cena.mp3' },
  jeopardy: { url: 'jeopardy.mp3' },
  learn: { url: 'this_is_a_good_opportunity_to_learn.mp3' },
  mayo: { url: 'is-mayonnaise-an-instrument.mp3' },
  me: { url: 'its-me-mario.mp3' },
  mistakes: { url: 'you_cant_improve_until_you_make_mistakes.mp3' },
  moreyouknow: { url: 'the-more-you-know.mp3' },
  needit: { url: 'dont_need_it.mp3' },
  nextlevel: { url: 'next_level.mp3' },
  niceu: { url: 'mic-check-ep_2.mp3' },
  nochill: { url: 'no_chill.mp3' },
  noice: { url: 'nooice.mp3' },
  nothing: { url: 'nothing_that_can_stop_this_man.mp3.mp3' },
  nottoday: { url: 'not_today.mp3' },
  ok: { url: 'lil-jon-okay.mp3' },
  oof: { url: 'sm64_mario_oof.mp3' },
  oy: { url: 'oy_oy_oy.mp3' },
  playedyoself: { url: 'dont-ever-play-yourself-dj-khaled-vine.mp3' },
  power: { url: 'i-have-the-power.mp3' },
  proud: { url: 'gaben_im_very_proud.mp3' },
  ready: { url: 'john-cena-prank-call.mp3' },
  rekt: { url: 'riggity-riggity-wrecked-son.mp3' },
  rip: {
    url: 'vicetone-tony-igy-astronomia-2014-audiotrimmer.mp3',
    volume: 0.75,
  },
  sad: { url: 'the-price-is-right-losing-horn.mp3' },
  sorry: { url: 'sorry.mp3' },
  spooky: { url: 'the-x-files-theme.mp3' },
  surprise: { url: 'surprise-motherfucker.mp3' },
  trap: { url: 'admiral-ackbar-its-a-trap-.mp3' },
  treat: { url: 'treat-yo-self.mp3' },
  unreal: { url: 'that_was_unreal.mp3' },
  vitas: { url: 'vitas.mp3', volume: 0.5 },
  what: { url: 'lil-jon-what.mp3' },
  wisdom: { url: 'making_mistakes_is_the_path_to_wisdom.mp3' },
  woo: { url: 'coming_through_with_the_woooo.mp3' },
  wow: { url: 'wow.mp3' },
  yay: { url: 'grunt_birthday_sound.mp3' },
  yeah: { url: 'yeeeeeeeah.mp3' },
};

for (const command in sound_bytes) {
  sound_bytes[command].url = `./sounds/${sound_bytes[command].url}`;
}

module.exports = {
  sound_bytes,
};
